# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Flutwellen
                                 A QGIS plugin
 https://github.com/RetepRelleum/flutwelle
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-19
        copyright            : (C) 2026 by Retep Relleum
        email                : retep.relleum@bluewin.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load Flutwellen class from file Flutwellen.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lib.Flutwelle import Flutwelle
    return Flutwelle(iface)

