# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Flutwelle
                                 A QGIS plugin
 Flutwelle
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-10
        git sha              : $Format:%H$
        copyright            : (C) 2026 by retep relleum
        email                : retep.relleum@bluewin.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/


THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
import matplotlib.pyplot as plt
import numpy as np
from .Layer import DammL, IntL
from .Raster import Raster
from qgis.core import QgsPoint, QgsPointXY
import qgis.utils
from qgis.gui import QgsVertexMarker
from qgis.PyQt.QtGui import QColor


class Querschnitt3D:
    def __init__(self, laenge, la, qb, path, projekt=''):
        laenge = round(laenge / 10) * 10
        self.raster = Raster(path)
        self.inten = IntL(path)
        self.damm = DammL(path)
        p1, p2 = self.inten.getPlPr(laenge)
        p3, p4 = self.inten.getPlPr(laenge - 10)
        p5, p6 = self.inten.getPlPr(laenge - 20)
        lx = p1.distance(p2)
        dx_ = (p1.x() - p2.x()) / lx
        dy_ = (p1.y() - p2.y()) / lx
        px = QgsPoint(p1.x() + dx_ * la, p1.y() + dy_ * la, 0)
        llx = int((lx + 2 * la))
        X1 = np.arange(0, llx, 0.5)
        Y1 = np.arange(0, llx, 0.5)
        x3 = np.arange(0, 20, 0.5)
        y3 = np.arange(0, 20, 0.5)
        X, Y = np.meshgrid(Y1, X1)
        Z = X.copy()
        Z1 = X.copy()
        Z2 = X.copy()
        Z3 = X.copy()
        Z4 = X.copy()
        for x in Y1:
            for y in X1:
                x_ = px.x() - dx_ * x + y * dy_
                y_ = px.y() - dy_ * x - y * dx_
                if y <= 20:
                    pk = QgsPoint(x_, y_)
                    z_ = self.raster.getValue(pk)
                    if y <= 10:
                        h1 = p1.z() + (p3.z() - p1.z()) / 10 * y
                        h2 = p1.m() + (p3.m() - p1.m()) / 10 * y
                        h3 = qb - 0.4
                        h4 = qb
                    else:
                        h1 = p3.z() + (p5.z() - p3.z()) / 10 * (y - 10)
                        h2 = p3.m() + (p5.m() - p3.m()) / 10 * (y - 10)
                        h3 = qb - 0.4
                        h4 = qb
                    if y == 0:
                        h3 = qb
                    if y == 20:
                        h3 = qb
                    if z_ <= h1 and x > la / 2 and x < llx - la / 2:
                        z1 = h1
                        z2 = h2
                    else:
                        z1 = np.nan
                        z2 = np.nan
                        z3 = np.nan
                    if z_ <= h3:
                        z3 = h3
                    else:
                        z3 = np.nan
                    if z_ <= h4:
                        z4 = h4
                    else:
                        z4 = np.nan
# self.setMarker( pk,2)
                else:
                    z_ = np.nan
                    z1 = np.nan
                    z2 = np.nan
                    z3 = np.nan
                    z4 = np.nan
                Z[int(x * 2)][int(y * 2)] = z_
                Z1[int(x * 2)][int(y * 2)] = z1
                Z2[int(x * 2)][int(y * 2)] = z2
                Z3[int(x * 2)][int(y * 2)] = z3
                Z4[int(x * 2)][int(y * 2)] = z4
        for x in X1:
            h3 = 100000
            for y in Y1:
                if h3 > Z[int(y * 2)][int(x * 2)]:
                    h3 = Z[int(y * 2)][int(x * 2)]
            if x < 20:
                y3[int(x * 2)] = h3

        Y1 = np.array([0, llx / 2, llx])
        X1 = np.array([0, 10, 20])
        plt.style.use('_mpl-gallery')
        fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
        ax.plot_surface(Y, X, Z, alpha=0.5, color='limegreen',
                        label='Gelaende', linewidth=0.5, edgecolor='gray')
        ax.plot_surface(Y, X, Z1, alpha=0.5, color='blue',
                        label='Quote Abfluss', linewidth=0.25, edgecolor='black')
        ax.plot_surface(Y, X, Z2, alpha=0.2, color='red',
                        label='Energielinienhoehe', linewidth=0.25, edgecolor='black')
        x = [0, 10, 20]
        xb = [20, 10, 0, 0, 10, 20, 20]
        y = [p1.z(), p3.z(), p5.z()]
        y1 = [p1.m(), p3.m(), p5.m()]
        y2 = [qb - 0.4, qb - 0.4, qb - 0.4, qb, qb, qb, qb - 0.4]

        ax.plot(x, y, zs=-llx / 100 * 5, zdir='x',
                label='Quote Abfluss', color='blue')
        ax.plot(x, y, zs=llx + llx / 100 * 5, zdir='x',
                label='Quote Abfluss)', color='blue')
        ax.plot(x, y1, zs=-llx / 100 * 5, zdir='x',
                label='Energielinienhoehe', color='red')
        ax.plot(x, y1, zs=llx + llx / 100 * 5, zdir='x',
                label='Energielinienhoehe', color='red')
        ax.plot(x3, y3, zs=-llx / 100 * 5, zdir='x',
                label='Gelaende', color='limegreen')
        ax.plot(x3, y3, zs=llx + llx / 100 * 5, zdir='x',
                label='Gelaende', color='limegreen')
        if qb > 0:
            ax.text(llx, 0, qb, 'Brücke', size=12, color='black',
                    ha='right', va='center_baseline')
            ax.plot(xb, y2, zs=-llx / 100.0 * 5.0, zdir='x',
                    label='Bruecke', color='gray')
            ax.plot(xb, y2, zs=llx + llx / 100.0 * 5.0, zdir='x',
                    label='Bruecke', color='gray')
            ax.plot_surface(Y, X, Z3, alpha=0.4, color='gray',
                            label='Bruecke', linewidth=0.25, edgecolor='black')
            ax.plot_surface(Y, X, Z4, alpha=0.4, color='gray',
                            label='Bruecke', linewidth=0.25, edgecolor='black')
        ax.text(llx, 0, p1.z(), 'Quote Abfluss',
                size=12, color='blue', ha='right', va='center')
        ax.text(llx / 2, 0, np.nanmax(Z), projekt,
                size=16, color='blue', ha='center', va='bottom')
        ax.text(llx, 0, p1.m(), 'Energielinienhöhe',
                size=12, color='red', ha='right', va='bottom')
        ax.text(llx, 0, np.nanmin(Z), 'Flussbett',
                size=12, color='green', ha='right', va='top')

        text = 'Koordinaten\n'
        text += f'{self.sep(int(p1.x()))} / {self.sep(int(p1.y()))}\n'
        text += self.damm.getData(laenge)
        ax.text(0, 0, np.nanmin(Z) + (np.nanmax(Z) - np.nanmin(Z)) / 4, text,
                size=10, color='black', ha='left', va='center_baseline', wrap=True)

        ax.text(llx / 2, llx, np.nanmax(Z), 'erstell mit Qgis Plugin Flutwelle gemäss CTGREF',
                size=7, color='grey', ha='center', va='center_baseline')
        ax.set_xlabel('m')
        ax.set_ylabel('m')
        ax.set_zlabel('mü.M.')

        ax.set_xlim(int(-llx / 100.0 * 5.0), int(llx + llx / 100.0 * 5.0))
        ax.set_ylim(int(-llx / 100.0 * 5.0), int(llx + llx / 100.0 * 5.0))

        plt.show()
        self.raster.setVisibility(False)

    def sep(self, s):
        ret = ''
        while s > 0:
            ret = f"{s % 1000}'{ret}"
            s = s // 1000
        return ret[:-1]

    def setMarker(self, pk, col):
        pnt = QgsPointXY(pk.x(), pk.y())
        canvas = qgis.utils.iface.mapCanvas()
        m = QgsVertexMarker(canvas)
        m.setCenter(pnt)
        m.setColor(QColor('Black'))
        m.setIconType(QgsVertexMarker.ICON_CIRCLE)
        m.setIconSize(4)
        m.setPenWidth(1)
        if col == 1:
            m.setFillColor(QColor(0, 200, 0))
        if col == 2:
            m.setFillColor(QColor(0, 0, 200))
        if col == 3:
            m.setFillColor(QColor(200, 0, 0))
        if col == 4:
            m.setFillColor(QColor(0, 200, 200))
